### ISSUE TITLE
Pre-work the upgrade for PHP 8

### ISSUE THREAD

**Issue by macintoshplus** [InExtenso/win32service#49]
See:
https://github.com/php/php-src/blob/57d9b94dea7e634ec4775faa8f33ae03d9db5ef6/UPGRADING.INTERNALS#L33

* [x] Upgrade the code to build for PHP 8.0
* [x] Convert return code to Exception:  Issue #56
* [x] Remove code for old Windows version:  Issue #57
* [x] Check argument value and throw ValueError if need: Issue #58

**Comment by macintoshplus** [comment]
See https://github.com/win32service/win32service/tree/v1.0.x

**Comment by faithfulman18** [comment]
Will support of php 8.0 be ready around time for the release ?

**Comment by macintoshplus** [comment]
> Will support of php 8.0 be ready around time for the release ?

Hi,

Thanks for your interest. The work on this extension is only on my free time. 
Help is greatly appreciated! 

Help can be
* write code
* update the documentation
* test the newest extension on your project and send feedback
* pay a day of work for this extension

For PHP 8, I work to improve this extension to make great and easier to use.
The future version is 1.0.0 :champagne:

**Comment by macintoshplus** [comment]
V1.0.0 released
